# Generated by Django 2.0.5 on 2018-05-22 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='abouteme',
            new_name='aboutme',
        ),
    ]
