# Generated by Django 2.0.5 on 2018-05-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticles',
            options={},
        ),
    ]
